### ISSUE TITLE
Can this be implemented without meta programming?

### ISSUE THREAD

**Issue by ablack3** [jreps/shinyModuleViewer#2]
Hi @jreps,

I'm wondering if the functionality this R package provides can be implemented without relying on [functions that write R code](https://github.com/jreps/shinyModuleViewer/blob/7e621b3ae9152f947afb820babd0f2bf10cce2f0/R/createShinyApp.R#L176)

While this is a powerful technique it is also hard to debug and maintain as I found out [working with it in ROhdsiWebApi.](https://github.com/OHDSI/ROhdsiWebApi/blob/f48f8f593b4e9e073e56669dcb5541b098548df8/extras/PackageMaintenance.R#L104) I'm wondering if it is possible to use an approach that would rely on [shiny modules ](https://shiny.rstudio.com/articles/modules.html)(R functions that implement specific UI and server logic) that get passed in to the Module Viewer. The Module View would be a fully functioning shiny app that could be run and tested on its own. Each module could also be viewed as its own app. 

Just some design thoughts to consider while this is still in early development.

**Comment by ablack3** [comment]
Some ideas from Sebastian Wolf on modular shiny apps
https://towardsdatascience.com/a-shiny-web-app-from-lego-truck-trailer-c977015bc6a9
https://zappingseb.github.io/biowarptruck/

**Comment by jreps** [comment]
This is code for creating a UI/server wrapper for shiny modules.  There will be a config file that specifies the models to include (plus inputs such as database details for keyring), then one of the functions in this package takes the config as input then installs/downloads the modules and creates the UI/server wrapper.  It would be possible to manually update the UI/server from an existing one if you don't want to create it with a function.  However, the UI/server wrapper is being designed as such a simple structure it really isn't very complex to create it on the fly and it looks a lot cleaner than having a lot of conditional statements (plus it is a lot more flexible and lets people add custom modules).

We are adding shiny tests into each analysis shiny module to make sure they work.  It should be possible to test the UI/server files that are created as well.

**Comment by ablack3** [comment]
Ok I think I understand. Instead of having a single shiny module viewer app that acts as the "truck bed" and would accept various modules as input you are creating a new lightweight shiny module viewer for each study.
